CREATE INDEX IF NOT EXISTS "idx_sales_invoices_customer_id" ON "sales_invoices"("customerId");
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_inventory_id" ON "sales_invoices"("inventoryId");
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_sales_user_id" ON "sales_invoices"("salesUserId");
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_section" ON "sales_invoices"("section");
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_payment_status" ON "sales_invoices"("paymentStatus");
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_delivery_status" ON "sales_invoices"("deliveryStatus");
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_payment_confirmed" ON "sales_invoices"("paymentConfirmed");
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_created_at" ON "sales_invoices"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_proc_orders_supplier_id" ON "proc_orders"("supplierId");
CREATE INDEX IF NOT EXISTS "idx_proc_orders_inventory_id" ON "proc_orders"("inventoryId");
CREATE INDEX IF NOT EXISTS "idx_proc_orders_created_by" ON "proc_orders"("createdBy");
CREATE INDEX IF NOT EXISTS "idx_proc_orders_section" ON "proc_orders"("section");
CREATE INDEX IF NOT EXISTS "idx_proc_orders_status" ON "proc_orders"("status");
CREATE INDEX IF NOT EXISTS "idx_proc_orders_payment_confirmed" ON "proc_orders"("paymentConfirmed");
CREATE INDEX IF NOT EXISTS "idx_proc_orders_created_at" ON "proc_orders"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_items_section" ON "items"("section");
CREATE INDEX IF NOT EXISTS "idx_items_name" ON "items"("name");
CREATE INDEX IF NOT EXISTS "idx_customers_type" ON "customers"("type");
CREATE INDEX IF NOT EXISTS "idx_customers_division" ON "customers"("division");
CREATE INDEX IF NOT EXISTS "idx_inventory_stocks_item_id" ON "inventory_stocks"("itemId");
CREATE INDEX IF NOT EXISTS "idx_inventory_stocks_inventory_id" ON "inventory_stocks"("inventoryId");
CREATE INDEX IF NOT EXISTS "idx_sales_invoice_items_invoice_id" ON "sales_invoice_items"("invoiceId");
CREATE INDEX IF NOT EXISTS "idx_sales_invoice_items_item_id" ON "sales_invoice_items"("itemId");
CREATE INDEX IF NOT EXISTS "idx_proc_order_items_order_id" ON "proc_order_items"("orderId");
CREATE INDEX IF NOT EXISTS "idx_proc_order_items_item_id" ON "proc_order_items"("itemId");
CREATE INDEX IF NOT EXISTS "idx_expenses_created_by" ON "expenses"("createdBy");
CREATE INDEX IF NOT EXISTS "idx_expenses_method" ON "expenses"("method");
CREATE INDEX IF NOT EXISTS "idx_expenses_created_at" ON "expenses"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_audit_logs_user_id" ON "audit_logs"("userId");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_action" ON "audit_logs"("action");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_created_at" ON "audit_logs"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_sales_invoices_section_payment_status" ON "sales_invoices"("section", "paymentStatus");
CREATE INDEX IF NOT EXISTS "idx_proc_orders_section_status" ON "proc_orders"("section", "status");
CREATE INDEX IF NOT EXISTS "idx_inventory_stocks_inventory_item" ON "inventory_stocks"("inventoryId", "itemId");
